from dataclasses import dataclass

from environs import Env

category_dict = {
    'franshizy': 'Франшизы',
    'internet_magazin': 'Интернет-магазины и IT',
    'obschestvennoe_pitanie': 'Общественное питание',
    'proizvodstvo': 'Производство',
    'razvlecheniya': 'Развлечения',
    'selskoe_hozyaystvo': 'Сельское хозяйство',
    'stroitelstvo': 'Строительство',
    'sfera_uslug': 'Сфера услуг',
    'torgovlya': 'Магазины и пункты выдачи заказов',
    'avtomobilnyi_biznes': 'Автобизнес',
    'krasota_i_ukhod': 'Красота и уход',
    'zdorove_i_medicina': 'Стоматология и медицина',
    'gostinicy_i_bazy_otdykha': 'Туризм',
    'drugoe': 'Другое'
}


@dataclass
class Hidden:
    # link: str
    delay: float
    tablename: str
    start_page: int
    pages: int
    db_username: str
    db_password: str
    db_local_port: int
    db_name: str
    db_echo: bool


def load_hidden_vars(path: str):
    env = Env()
    env.read_env()

    return Hidden(
        # link=env.str("LINK"),
        delay=env.float("DELAY"),
        tablename=env.str("TABLENAME"),
        start_page=env.int("START_PAGE"),
        pages=env.int("PAGES"),
        db_username=env.str("DB_USERNAME"),
        db_password=env.str("DB_PASSWORD"),
        db_local_port=env.int("DB_LOCAL_PORT"),
        db_name=env.str("DB_NAME"),
        db_echo=env.bool("DB_ECHO")
    )


hidden = load_hidden_vars(path='.env')

russia_eng = [
    'moskva_i_mo',
    'sankt_peterburg_i_lo',
    'adygeya',
    'altayskiy_kray',
    'bashkortostan',
    'buryatiya',
    'dagestan',
    'donetsk',
    'ingushetiya',
    'kabardino-balkariya',
    'kalmykiya',
    'karachaevo-cherkesiya',
    'kareliya',
    'kherson',
    'komi',
    'respublika_krym',
    'lugansk',
    'mariy_el',
    'mordoviya',
    'saha_yakutiya',
    'severnaya_osetiya',
    'tatarstan',
    'tyva',
    'udmurtiya',
    'hakasiya',
    'chechenskaya_respublika',
    'zabaykalskiy_kray',
    'kamchatskiy_kray',
    'krasnodarskiy_kray',
    'permskiy_kray',
    'primorskiy_kray',
    'stavropolskiy_kray',
    'habarovskiy_kray',
    'amurskaya_oblast',
    'arhangelskaya_oblast',
    'astrahanskaya_oblast',
    'belgorodskaya_oblast',
    'bryanskaya_oblast',
    'vladimirskaya_oblast',
    'volgogradskaya_oblast',
    'vologodskaya_oblast',
    'voronezhskaya_oblast',
    'ivanovskaya_oblast',
    'irkutskaya_oblast',
    'kaliningradskaya_oblast',
    'kaluzhskaya_oblast',
    'kemerovskaya_oblast',
    'kirovskaya_oblast',
    'kostromskaya_oblast',
    'kurganskaya_oblast',
    'kurskaya_oblast',
    'lipetskaya_oblast',
    'magadanskaya_oblast',
    'murmanskaya_oblast',
    'nizhegorodskaya_oblast',
    'novgorodskaya_oblast',
    'novosibirskaya_oblast',
    'omskaya_oblast',
    'orenburgskaya_oblast',
    'orlovskaya_oblast',
    'penzenskaya_oblast',
    'pskovskaya_oblast',
    'rostovskaya_oblast',
    'ryazanskaya_oblast',
    'samarskaya_oblast',
    'saratovskaya_oblast',
    'sahalinskaya_oblast',
    'sverdlovskaya_oblast',
    'smolenskaya_oblast',
    'tambovskaya_oblast',
    'tverskaya_oblast',
    'tomskaya_oblast',
    'tulskaya_oblast',
    'tyumenskaya_oblast',
    'ulyanovskaya_oblast',
    'chelyabinskaya_oblast',
    'yaroslavskaya_oblast',
    'sevastopol',
    'evreyskaya_ao',
    'nenetskiy_ao',
    'hanty-mansiyskiy_ao',
    'chukotskiy_ao',
    'yamalo-nenetskiy_ao',
]

russia_rus = {
    # 'Москва': 'Москва и МО',
    # 'Санкт-Петербург': 'Санкт-Петербург и ЛО',
    # 'адыгея': 'Республика Адыгея',
    # 'алтай': 'Алтайский край',
    # 'башкортостан': 'Республика Башкортостан',
    # 'бурятия': 'Республика Бурятия',
    # 'дагестан': 'Республика Дагестан',
    # 'донецк': 'Донецк (Донецкая область)',
    # 'ингушетия': 'Республика Ингушетия',
    # 'Кабардино-Балкария': 'Республика Кабардино-Балкария',
    # 'калмыкия': 'Республика Калмыкия',
    # 'Карачаево-Черкесия': 'Республика Карачаево-Черкесия',
    # 'карелия': 'Республика Карелия',
    # 'херсон': 'Херсон',
    # 'коми': 'Республика Коми',
    # 'крым': 'Республика Крым',
    # 'луганск': 'Луганск',
    # 'марий ': 'Республика Марий Эл',
    # 'мордовия': 'Республика Мордовия',
    # 'якутия': 'Республика Якутия',
    # 'осетия': 'Республика Северная Осетия-Алания',
    # 'татарстан': 'Республика Татарстан',
    # 'тыва': 'Республика Тыва',
    # 'удмуртская': 'Республика Удмуртская',
    # 'хакасия': 'Республика Хакасия',
    # 'чеченская': 'Республика Чеченская',
    # 'забайкальский': 'Забайкальский край',
    # 'камчатский': 'Камчатский край',
    # 'краснодарский': 'Краснодарский край',
    # 'пермский': 'Пермский край',
    # 'приморский': 'Приморский край',
    # 'ставропольский': 'Ставропольский край',
    # 'хабаровский': 'Хабаровский край',
    # 'амурская': 'Амурская область',
    # 'архангельская': 'Архангельская область',
    # 'астраханская': 'Астраханская область',
    # 'белгородская': 'Белгородская область',
    # 'брянская': 'Брянская область',
    # 'владимирская': 'Владимирская область',
    # 'волгоградская': 'Волгоградская область',
    # 'вологодская': 'Вологодская область',
    # 'воронежская': 'Воронежская область',
    # 'ивановская': 'Ивановская область',
    # 'иркутская': 'Иркутская область',
    # 'калининградская': 'Калининградская область',
    # 'калужская': 'Калужская область',
    # 'кемеровская': 'Кемеровская область',
    # 'кировская': 'Кировская область',
    # 'костромская': 'Костромская область',
    # 'курганская': 'Курганская область',
    # 'курская': 'Курская область',
    # 'липецкая': 'Липецкая область',
    # 'магаданская': 'Магаданская область',
    # 'мурманская': 'Мурманская область',
    # 'нижегородская': 'Нижегородская область',
    # 'новгородская': 'Новгородская область',
    # 'новосибирская': 'Новосибирская область',
    # 'омская': 'Омская область',
    # 'оренбургская': 'Оренбургская область',
    # 'орловская': 'Орловская область',
    # 'пензенская': 'Пензенская область',
    # 'псковская': 'Псковская область',
    # 'ростовская': 'Ростовская область',
    # 'рязанская': 'Рязанская область',
    # 'самарская': 'Самарская область',
    # 'саратовская': 'Саратовская область',
    # 'сахалинская': 'Сахалинская область',
    # 'свердловская': 'Свердловская область',
    # 'смоленская': 'Смоленская область',
    # 'тамбовская': 'Тамбовская область',
    # 'тверская': 'Тверская область',
    # 'томская': 'Томская область',
    # 'тульская': 'Тульская область',
    # 'тюменская': 'Тюменская область',
    # 'ульяновская': 'Ульяновская область',
    # 'челябинская': 'Челябинская область',
    # 'ярославская': 'Ярославская область',
    'севастоп': 'Севастополь,Республика Крым',
    'Еврейская': 'Еврейская',
    'ямало': 'Ямало-Ненецкий автономный округ',
    'ханты': 'Ханты-Мансийский автономный округ - Югра',
    'чукотский': 'Чукотский автономный округ',
    'ямало': 'Ямало-Ненецкий автономный округ',
}
